inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'test/*.rb'
  SuggestExtensions: false
Layout/HashAlignment:
  Exclude:
    - '*.gemspec'
Layout/LineLength:
  AllowedPatterns:
    - !ruby/regexp /\A\s*# /
Lint/MissingSuper:
  Exclude:
    - 'lib/tls_map/cli/cli.rb'
Metrics/AbcSize:
  Exclude:
    - 'lib/unisec/properties.rb'
Metrics/ClassLength:
  Exclude:
    - 'lib/unisec/properties.rb'
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/unisec/properties.rb'
Naming/MethodParameterName:
  Exclude:
    - 'lib/unisec/surrogates.rb'
Style/Documentation:
  Exclude:
    - 'lib/unisec/cli/surrogates.rb'
    - 'lib/unisec/utils.rb'
